#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "warpgate"
name = "Warpgate"
description.en = "Secure and authenticated SSH, HTTP, MYSQL and Postgres tunnels"
description.fr = "Tunnels SSH, HTTP, MYSQL and Postgres sécurisés et authentifiés"

version = "0.21.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://warpgate.null.page/"
admindoc = "https://warpgate.null.page/docs/"
code = "https://github.com/warp-tech/warpgate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64","arm64" ]
multi_instance = false

ldap = false
sso = false

disk = "10M"
ram.build = "80M"
ram.runtime = "30M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "warpgate"
    amd64.url = "https://github.com/warp-tech/warpgate/releases/download/v0.21.0/warpgate-v0.21.0-x86_64-linux"
    amd64.sha256 = "23397f983432600327f248dda7abe8e55fdb9e7a7a574ed197a80ab9fe4ff285"

    arm64.url = "https://github.com/warp-tech/warpgate/releases/download/v0.21.0/warpgate-v0.21.0-arm64-linux"
    arm64.sha256 = "e95e10fb5c6bb162ce6a7de9dc62342e459d27c041c4aaa56c1e05024f3dcf6d"
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^warpgate-.*-x86_64-linux$"
    autoupdate.asset.arm64 = "^warpgate-.*-arm64-linux$"
    autoupdate.upstream = "https://github.com/warp-tech/warpgate"
    

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    ssh.exposed = "TCP"
    mysql.exposed = "TCP"
    postgres.exposed = "TCP"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
