#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "warpgate"
name = "Warpgate"
description.en = "Secure and authenticated SSH, HTTP, MYSQL and Postgres tunnels"
description.fr = "Tunnels SSH, HTTP, MYSQL and Postgres sécurisés et authentifiés"

version = "0.20.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://warpgate.null.page/"
admindoc = "https://warpgate.null.page/docs/"
code = "https://github.com/warp-tech/warpgate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64","arm64" ]
multi_instance = false

ldap = false
sso = false

disk = "10M"
ram.build = "80M"
ram.runtime = "30M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "warpgate"
    amd64.url = "https://github.com/warp-tech/warpgate/releases/download/v0.20.2/warpgate-v0.20.2-x86_64-linux"
    amd64.sha256 = "5e918f7b546bbe258e38df7140605066f4e85516de70a7a224066882a8f57012"

    arm64.url = "https://github.com/warp-tech/warpgate/releases/download/v0.20.2/warpgate-v0.20.2-arm64-linux"
    arm64.sha256 = "a3c7d8508899c36df04ec6d5c9029b3c6d60351983bd6dc156514868dcb5ee7e"
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^warpgate-.*-x86_64-linux$"
    autoupdate.asset.arm64 = "^warpgate-.*-arm64-linux$"
    autoupdate.upstream = "https://github.com/warp-tech/warpgate"
    

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    ssh.exposed = "TCP"
    mysql.exposed = "TCP"
    postgres.exposed = "TCP"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
