#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "warpgate"
name = "Warpgate"
description.en = "Secure and authenticated SSH and HTTPS tunnels"
description.fr = "Tunnels SSH, HTTPS sécurisés et authentifiés"

version = "0.16.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://warpgate.null.page/"
admindoc = "https://warpgate.null.page/docs/"
code = "https://github.com/warp-tech/warpgate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64","arm64" ]
multi_instance = false

ldap = false
sso = false

disk = "10M"
ram.build = "80M"
ram.runtime = "30M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "warpgate"
    amd64.url = "https://github.com/warp-tech/warpgate/releases/download/v0.16.0/warpgate-v0.16.0-x86_64-linux"
    amd64.sha256 = "c95186fdacff3944538387bd072f89e7abb014a18f4f9b31e20c08028f27c4a3"

    arm64.url = "https://github.com/warp-tech/warpgate/releases/download/v0.16.0/warpgate-v0.16.0-arm64-linux"
    arm64.sha256 = "61358fd1e2b1d397ba608fbbedc5cc66a9cbc655c08becbb8876ae20677ad405"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^warpgate-.*-x86_64-linux$"
    autoupdate.asset.arm64 = "^warpgate-.*-arm64-linux$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
