#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "warpgate"
name = "Warpgate"
description.en = "Secure and authenticated SSH and HTTPS tunnels"
description.fr = "Tunnels SSH, HTTPS sécurisés et authentifiés"

version = "0.16.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://warpgate.null.page/"
admindoc = "https://warpgate.null.page/docs/"
code = "https://github.com/warp-tech/warpgate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "10M"
ram.build = "80M"
ram.runtime = "30M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    extract = false
    rename = "warpgate"
    url = "https://github.com/warp-tech/warpgate/releases/download/v0.16.0/warpgate-v0.16.0-x86_64-linux"
    sha256 = "c95186fdacff3944538387bd072f89e7abb014a18f4f9b31e20c08028f27c4a3"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    #[resources.apt]
    #packages = "mariadb-server"

    #[resources.database]
    #type = "mysql"
