#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY EXTERNAL_HOST IN WARPGATE.YAML
#=================================================
ynh_script_progression "Updating $app configuration..."

ynh_write_var_in_file --file=$install_dir/warpgate.yaml --key=external_host --value=$new_domain

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
