#!/bin/bash

#source ./_common.sh
source /usr/share/yunohost/helpers

ynh_app_config_apply() {
    _ynh_app_config_apply
    ynh_config_add --template="warpgate.yaml" --destination="$install_dir/warpgate.yaml"
}

#=================================================
# SELECT THE ACTION FOLLOWING THE GIVEN ARGUMENT
#=================================================
ynh_app_config_run "$1"