#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x $install_dir/warpgate

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Secure and authenticated SSH, HTTP, MYSQL and Postgres tunnels" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL WARPGATE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
 	ynh_hide_warnings ./warpgate --config=$install_dir/warpgate.yaml unattended-setup --data-path="$data_dir" --ssh-port=$port_ssh --http-port=$port --mysql-port=$port_mysql --postgres-port=$port_postgres --admin-password=$password --database-url="postgres://$db_user:$db_pwd@127.0.0.1:5432/$db_name" --external-host="$domain"
popd

chown -R $app:$app $install_dir
chown -R $app:$app $data_dir

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
