#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# ENCRYPTION KEY
#=================================================
ynh_script_progression "Generating encryption key..."

warpgate_encryption_key=$(openssl rand -base64 32)

ynh_app_setting_set --key=warpgate_encryption_key --value=$warpgate_encryption_key

ynh_config_add --template="env" --destination="$install_dir/.env"

chown $app:$app $install_dir/.env
chmod o-rwx $install_dir/.env

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod +x $install_dir/warpgate

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Secure access to SSH, HTTPS, RDP, VNC, Kubernetes, PostgreSQL and MySQL" --log=systemd

#=================================================
# INSTALL WARPGATE
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
 	ynh_hide_warnings ./warpgate --config=$install_dir/warpgate.yaml unattended-setup --data-path="$data_dir" --http-port=$port --admin-password=$password --database-url="postgres://$db_user:$db_pwd@127.0.0.1:5432/$db_name" --external-host="$domain"
popd

chown -R $app:$app $install_dir
chown -R $app:$app $data_dir

#=================================================
# ADD WARPGATE.YAML
#=================================================
ynh_script_progression "Upgrading warpgate config..."

ynh_config_add --template="warpgate.yaml" --destination="$install_dir/warpgate.yaml"

chown $app:$app $install_dir/warpgate.yaml

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="Cookie domain configured"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
