#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="warpgate.yaml"

chmod +x $install_dir/warpgate

#=================================================
# UPDATE WARPGATE.YAML
#=================================================
if ynh_app_upgrading_from_version_before_or_equal_to 0.18.0~ynh1; then
	ynh_script_progression "Updating warpgate.yaml..."
    
    ynh_write_var_in_file --file=$install_dir/warpgate.yaml --key=external_host --value=$domain
    ynh_write_var_in_file --file=$install_dir/warpgate.yaml --key=enable --value=true --after="mysql:"
    ynh_replace --match=22 --replace=$port_ssh --file=$install_dir/warpgate.yaml
    ynh_replace --match=33306 --replace=$port_mysql --file=$install_dir/warpgate.yaml
    ynh_replace --match=55432 --replace=$port_postgres --file=$install_dir/warpgate.yaml
fi

if ynh_app_upgrading_from_version_before_or_equal_to 0.21.0~ynh1; then
    ynh_script_progression "Applying postrgresql fix..."
    psql "postgresql://$db_user:$db_pwd@localhost:5432/$db_name" -c "CREATE OR REPLACE FUNCTION json_text_like(json, text) RETURNS boolean AS \$\$ SELECT \$1::text LIKE \$2; \$\$ LANGUAGE sql IMMUTABLE STRICT; CREATE OPERATOR ~~ (LEFTARG = json, RIGHTARG = text, PROCEDURE = json_text_like);"
fi
#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Secure and authenticated SSH, HTTP, MYSQL and Postgres tunnels" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
